# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Gradle and pnpm build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gradle:
    name: Gradle Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build

  api_docs:
    name: Build API Reference Docs
    runs-on: ubuntu-latest
    needs: [ gradle ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Generate API Reference with Dokka
        uses: gradle/gradle-build-action@v3
        with:
          arguments: dokkaHtml

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install Vercel CLI
        run: pnpm i -g vercel

      - name: Login to Vercel
        run: vercel login theonlytails@theonlytails.com --token ${{ env.VERCEL_TOKEN }}

      - name: Link project to Vercel
        run: vercel link ./docs --yes

      - name: Deploy to Vercel
        run: vercel deploy
